name: "Deploy: Production"
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    environment: Production
    runs-on: ubuntu-latest
    env:
      TMDB_API_URL: ${{ secrets.REACT_APP_TMDB_API_URL }}
      TMDB_API_ACCESS_TOKEN: ${{ secrets.REACT_APP_TMDB_API_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Create .env file and update Vercel .env
        run: |
          touch .env
          echo REACT_APP_TMDB_API_URL="${{ env.TMDB_API_URL }}" >> .env
          echo REACT_APP_TMDB_API_ACCESS_TOKEN="${{ env.TMDB_API_ACCESS_TOKEN }}" >> .env

      - name: Update Vercel .env file with local .env
        run: cat .env >> .vercel/.env.production.local

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
